### ISSUE TITLE
func AddTask problem

### ISSUE THREAD

**Issue by Rtuty** [volyanyk/todoist#4]
When I use the add Task function from this package, a problem occurs. 
Unable to evaluate expression: could not find symbol value for tasks

![image](https://user-images.githubusercontent.com/45632342/233865786-c885ec2a-bf66-4a57-955d-bf109f6007b8.png)

![image](https://user-images.githubusercontent.com/45632342/233865768-55b3109a-d786-4aec-a327-3516eaa3d593.png)

Please tell me how I can solve this problem. Thank you in advance!

**Comment by volyanyk** [comment]
Hey @Rtuty .
Sure, I will check that this week and provide a fix.

**Comment by volyanyk** [comment]
Dear @Rtuty , thank you for your request.
The fix is provided and pushed to the https://pkg.go.dev/github.com/volyanyk/todoist@v1.0.2

**Comment by Rtuty** [comment]
Everything is working well now, thanks a lot!
